version: "3.8"
services:
  urlwatch-ui:
    image: localhost/urlwatch-ui:latest
    container_name: urlwatch-ui
    expose:
      - "3000"
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./data
        target: /root/.urlwatch

    environment:
      - EDITOR=/usr/bin/vi
      - TZ=Asia/Tokyo

    networks:
      - containya-network

networks:
  containya-network:
    external: true
